### ISSUE TITLE
AGOL checking

### ISSUE THREAD

**Issue by green3g** [Bolton-and-Menk-GIS/restapi#4]
I've been following this recently and I noticed it looks like you're adding AGOL support for tokens (which is awesome!), but I think you should be checking for urls that contain `arcgis.com` instead of `www.arcgis.com` on this line: 

https://github.com/Bolton-and-Menk-GIS/restapi/blob/5fba7ddf04f2decd736e00c578b7d5fd83869b4c/restapi/rest_utils.py#L318

Our organization account url is in the format of `organization.maps.arcgis.com` and our rest endpoint is `services3.arcgis.com/xxxxxxxxxxxxxxxxx/arcgis/rest/services`

Cheers.

**Comment by CalebM1987** [comment]
Hi,

Thank you for your concerns.  This is actually something that is not yet in production.  I am currently working on doing a complete rewrite in parallel for an official release of version 1.0.  The original `restapi` is really messy and has a lot of inefficiencies.  That being said, one of the things I wanted to add was AGOL support.

What you are seeing in line 318 of rest_utils is not actually going to cause a problem.  When you authenticate against AGOL, there are actually 2 tokens that get generated.  The first token is to authenticate against AGOL itself (I think), and the second token is created specifically for your organization.  So the line where it is checking to see if `www.arcgis.com` is in the url, it is not the url of the service you pass in, it is the `tokenServicesUrl` that is gained from a call to `services3.arcgis.com/xxxxxxxxxxxxxxxxx/arcgis/rest/services/info`.  

I'll explain what the code does so it will make more sense as to how/why I do the check for AGOL services.  The steps below are how it generates a token for AGOL:
1. `restapi` will make a call to `services3.arcgis.com/xxxxxxxxxxxxxxxxx/arcgis/rest/services/info`, this returns JSON that contains the `tokenServicesUrl`.  This is where it is checking for AGOL services.
2. if it is an AGOL service, the token services url will always be `https://www.arcgis.com/sharing/generateToken`. if `www.arcgis.com` is in this url, then it most likely is an AGOL service.
   - if it is your own REST services directory from an ArcGIS Server instance, it will be something like `https://your-domain.com/arcgis/tokens/`.  
   - `restapi` will always use the `tokenServicesUrl` so that it can always find the valid endpoint to the token service
3. use the `tokenServicesUrl` (the `www.arcgis.com/sharing/generateToken` address) to generate a generic token for AGOL.
4. `restapi` will then make a call to `www.arcgis.com/sharing/portals/self` to find out what organization the user belongs to based on their AGOL credentials.  This returns a JSON response containing info on your organization and user profile.  The important piece that is grabbed from here is the `urlKey`.  This is what stores your organization prefix, which is used to generate a token specifically for your organization, i.e. `organization.maps.arcgis.com`.
5. `restapi` will call `www.arcgis.com/sharing/rest/generateToken` one more time to generate the token for your org by passing in the `organization.maps.arcgis.com` domain as the `referer`. 
6. `restapi` now has a valid token and can access your services on `services3.arcgis.com/xxxxxxxxxxxxxxxxx/arcgis/rest/services`.

Does that all make sense?  So long story short, it never checks if `www.arcgis.com` is in your organization url, it just checks if that is in the `tokenServicesUrl`.  Therefore, I do not think this is an issue.  Please let me know when you have read this so I can close this ticket.  

And thank you for the feedback, I appreciate the concerns!  Definitely continue to to leave comments like this if you see anything suspect in my code.  I can see why this looked like a potential oversight on my part.
- Caleb

**Comment by green3g** [comment]
Thanks for the explanation, that makes perfect sense. I didn't realize AGO ends up generating two tokens. I'll keep an eye out for the new release, this looks like it will be really helpful with what I'm going to be working on in the near future.

**Comment by CalebM1987** [comment]
Excellent!  Yes, I did not realize that either until I tested.  I generated one token then it was saying it wasn't valid, so then I had to poke around and see that a second token was necessary. 

And yes, I use this module almost daily.  I'm hoping to have the official version 1.0 release out in the next month or so.  You can clone the version1.0 branch right now, as it is fairly stable.  I haven't done much at all in the admin module yet, so a lot of stuff in there may be broken.
