### ISSUE TITLE
Python 2.7.8 - AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by MikeTownshend** [Bolton-and-Menk-GIS/restapi#5]
Good Morning,

This appears to be a similar issue as one previously posted, however, this is on a Windows box and not Ubuntu.

I am using restapi to harvest data from an existing arcgis server map services and save it as a shapefile.  The parkage runs perfectly except for when a feature class within the map document contains an alias different from the field name.  In those cases I get an error like the following:

AttributeError: 'NoneType' object has no attribute 'name'

The feature class field name is "Name", however, the alias for this field is ParcelID.

The attached file contains the paths to the rest end points I am using.  

[download_with_alias.txt](https://github.com/Bolton-and-Menk-GIS/restapi/files/495534/download_with_alias.txt)

**Comment by MikeTownshend** [comment]
The alias field may not be the causing the error.  I am now noticing that lyr.list_fields() does not include the shape field even though the rest endpoint does return it.

**Comment by CalebM1987** [comment]
Hi Mike,

I am not sure why you are getting that error, but I don't think it has to do with the fields (though it could).  I have identified a few problems with your script and I was able to pull parcels from the REST endpoint using the following script:

``` py
import restapi  #version 1.0
import os

# connect to Kent County Deleware rest services
rest_url = 'http://co.kent.de.us/arcgis/rest/services/KentCountyParcels/MapServer'

parcels = restapi.MapService(rest_url)

# access parcels layer
lyr = parcels.layer("Kent County Parcels") #not case sensitive, also supports wildcard search (*)
# could have also passed in the id of 0 for the above ^

# make scratch folder first
# folder = os.path.join(os.environ['USERPROFILE'], r'D:\DTIGISData')
# this looks wrong, os.environ['USERPROFILE'] should return something like:
# r"C:\Users\your_username"  on windows, so you are trying to combine that with
# D:\DTIGISData

#folder = r'C:\Users\calebma\Desktop\Kent'  # this is what I used in my test
folder =  r'D:\DTIGISData'
if not os.path.exists(folder):
    os.makedirs(folder)

# export layer to shapefile (can also call from Map Service)
output = os.path.join(folder, 'KC_Parcels.shp')
# maxRecordCount is 1000, may want to use the get_all param to True for the old version
# or, it is has been renamed in version 1.0 to exceed_limit
lyr.layer_to_fc(output)

# the above will only return the first 1000 features, you can get all by doing one of the following:
#   get_all=True OR exceed_limit=True if using new version 1.0 (still in development at this time)
# lyr.layer_to_fc(output, exceed_limit=True) <- will get all features, but may take a while as it has to
#   get chunks of 1000 features from the server....
```

Pay close attention to the comments, as I tried to provide some pointers.  One very important thing, I am using the new version, which is not quite ready for production (as a whole package) because I still need to rewrite large parts of the open source part and the admin console.  

But, I think for doing things like extracting data, the core of the updated restapi version is pretty stable and I am actually using it in production.  I would suggest getting the staging or "developer" edition of [restapi version 1.0 from the branch here](https://github.com/Bolton-and-Menk-GIS/restapi/tree/version1), and try running the script I provided.

One thing to note, in the service you are wanting to extract data from, they are using the default `maxRecordCount` of 1000, you can get around this in `restapi` by setting a parameter in the `restapi.MapServiceLayer.layer_to_fc()` method.  In the old version, the parameter is called `get_all`, and in the new version it has been renamed to `exceed_limit`.  So you would just set the parameter like this in the arguments: `exceed_limit=True`.

I hope this helps.  I have been a little slow at getting the version 1.0 release fully built, but hopefully I can get it done soon.  It offers lots of improvements and is more efficient than the old version.

**Comment by MikeTownshend** [comment]
Thank you.  The os.environ in the path was an artifact from when I was trying to run this elsewhere.
Very strange since I was able to export other layers in the same services folder without error.  In any case it worked and again I thank you.

I'll mess around with 1.0.  Still trying to figure out how to run these scripts behind a corporate firewall that requires authentication.  If I run into problems again using 1.0 I'll post another comment.

**Comment by CalebM1987** [comment]
No problem, glad that worked.  I am going to close this as an issue resolved.  If you are attempting to access secured REST endpoints, the `restapi` module does support token based authentication and using a proxy.  Have a look at the examples on the home page of this repo.

If you have future problems, I can also be reached at caleb.mackey@.gmail.com.
